import { packState } from './utils';
import { MOVE_ID, POSITION_ID, COUNT } from './constants';
import { Count, PositionId } from './types';

export const INITIAL_STATE = packState(POSITION_ID.OPEN, COUNT.RIGHT);

export const TRANSITIONS_CONFIG: Record<
    ReturnType<typeof packState<PositionId, Count>>,
    { [key: string]: ReturnType<typeof packState<PositionId, Count>> }
> = {
    [packState(POSITION_ID.OPEN, COUNT.RIGHT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.OPEN, COUNT.LEFT),
        [MOVE_ID.STRAIGHT_TURN]: packState(POSITION_ID.OPEN, COUNT.LEFT),
        [MOVE_ID.STRAIGHT_TURN_WITH_HAND_CHANGE]: packState(POSITION_ID.HANDSHAKE_REVERSED, COUNT.LEFT),
        [MOVE_ID.STRAIGHT_TURN_SELF]: packState(POSITION_ID.OPEN, COUNT.LEFT),
        [MOVE_ID.STRAIGHT_TURN_WITH_HAND_CHANGE_SELF]: packState(POSITION_ID.HANDSHAKE, COUNT.LEFT),
        [MOVE_ID.TWO_HAND_TURN]: packState(POSITION_ID.CROSSED_HANDS_LEFT, COUNT.LEFT),
        [MOVE_ID.HAMMERLOCK_TURN]: packState(POSITION_ID.HAMMERLOCK_LEFT, COUNT.LEFT),
        [MOVE_ID.HAMMERLOCK_TURN_SELF]: packState(POSITION_ID.HAMMERLOCK_LEFT_SELF, COUNT.LEFT),
        [MOVE_ID.DEAD_TURN]: packState(POSITION_ID.OPEN, COUNT.LEFT),
        [MOVE_ID.CROSS_BODY_LEAD]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.ABDOMINAL_TOUCH_TURN_SELF]: packState(POSITION_ID.HANDSHAKE, COUNT.LEFT),
        [MOVE_ID.SLIDE]: packState(POSITION_ID.OPEN, COUNT.LEFT),
    },
    [packState(POSITION_ID.OPEN, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_DOUBLE_TURN]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN_WITH_HAND_CHANGE]: packState(POSITION_ID.HANDSHAKE, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN_SELF]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN_WITH_HAND_CHANGE_SELF]: packState(POSITION_ID.HANDSHAKE_REVERSED, COUNT.RIGHT),
        [MOVE_ID.CLOSE_IN_TURN]: packState(POSITION_ID.CLOSED_HALF, COUNT.RIGHT),
        [MOVE_ID.TWO_HAND_TURN]: packState(POSITION_ID.CROSSED_HANDS_RIGHT, COUNT.RIGHT),
        [MOVE_ID.HAMMERLOCK_TURN]: packState(POSITION_ID.HAMMERLOCK_RIGHT, COUNT.RIGHT),
        [MOVE_ID.HAMMERLOCK_TURN_SELF]: packState(POSITION_ID.HAMMERLOCK_RIGHT_SELF, COUNT.RIGHT),
        [MOVE_ID.DEAD_TURN]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.WALK_ENTRY]: packState(POSITION_ID.WALK, COUNT.RIGHT),
        [MOVE_ID.CROSS_BODY_LEAD]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.ABDOMINAL_TOUCH_TURN_SELF]: packState(POSITION_ID.HANDSHAKE_REVERSED, COUNT.RIGHT),
        [MOVE_ID.SLIDE]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
    },
    [packState(POSITION_ID.CLOSED_HALF, COUNT.RIGHT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.CLOSED_HALF, COUNT.LEFT),
        [MOVE_ID.CROSS_BODY_LEAD]: packState(POSITION_ID.CLOSED_HALF, COUNT.RIGHT),
        [MOVE_ID.CARESS]: packState(POSITION_ID.CLOSED_FULL, COUNT.LEFT),
        [MOVE_ID.STEP_AWAY]: packState(POSITION_ID.OPEN, COUNT.LEFT),
        [MOVE_ID.SLIDE]: packState(POSITION_ID.CLOSED_HALF, COUNT.LEFT),
    },
    [packState(POSITION_ID.CLOSED_HALF, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.CLOSED_HALF, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.CLOSE_IN_TURN]: packState(POSITION_ID.CLOSED_HALF, COUNT.RIGHT),
        [MOVE_ID.WALK_ENTRY]: packState(POSITION_ID.WALK, COUNT.RIGHT),
        [MOVE_ID.CROSS_BODY_LEAD]: packState(POSITION_ID.CLOSED_HALF, COUNT.RIGHT),
        [MOVE_ID.CARESS]: packState(POSITION_ID.CLOSED_FULL, COUNT.RIGHT),
        [MOVE_ID.STEP_AWAY]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.SLIDE]: packState(POSITION_ID.CLOSED_HALF, COUNT.RIGHT),
    },
    [packState(POSITION_ID.CLOSED_FULL, COUNT.RIGHT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.CLOSED_FULL, COUNT.LEFT),
        [MOVE_ID.STEP_AWAY]: packState(POSITION_ID.OPEN, COUNT.LEFT),
    },
    [packState(POSITION_ID.CLOSED_FULL, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.CLOSED_FULL, COUNT.RIGHT),
        [MOVE_ID.STEP_AWAY]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
    },
    [packState(POSITION_ID.HANDSHAKE, COUNT.RIGHT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.HANDSHAKE, COUNT.LEFT),
        [MOVE_ID.STRAIGHT_TURN_SELF]: packState(POSITION_ID.HANDSHAKE, COUNT.LEFT),
        [MOVE_ID.STRAIGHT_TURN_WITH_HAND_CHANGE_SELF]: packState(POSITION_ID.OPEN, COUNT.LEFT),
    },
    [packState(POSITION_ID.HANDSHAKE, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.HANDSHAKE, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN]: packState(POSITION_ID.HANDSHAKE, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN_WITH_HAND_CHANGE]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN_SELF]: packState(POSITION_ID.HANDSHAKE, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN_WITH_HAND_CHANGE_SELF]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.CLOSE_IN_TURN]: packState(POSITION_ID.CLOSED_FULL, COUNT.RIGHT),
        [MOVE_ID.CUDDLING_ENTRY]: packState(POSITION_ID.CUDDLING, COUNT.RIGHT),
    },
    [packState(POSITION_ID.HANDSHAKE_REVERSED, COUNT.RIGHT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.HANDSHAKE_REVERSED, COUNT.LEFT),
        [MOVE_ID.STRAIGHT_TURN]: packState(POSITION_ID.HANDSHAKE_REVERSED, COUNT.LEFT),
        [MOVE_ID.STRAIGHT_TURN_WITH_HAND_CHANGE]: packState(POSITION_ID.OPEN, COUNT.LEFT),
        [MOVE_ID.STRAIGHT_TURN_SELF]: packState(POSITION_ID.HANDSHAKE_REVERSED, COUNT.LEFT),
        [MOVE_ID.STRAIGHT_TURN_WITH_HAND_CHANGE_SELF]: packState(POSITION_ID.OPEN, COUNT.LEFT),
        [MOVE_ID.CLOSE_IN_TURN]: packState(POSITION_ID.CLOSED_HALF, COUNT.LEFT),
    },
    [packState(POSITION_ID.HANDSHAKE_REVERSED, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.HANDSHAKE_REVERSED, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN_SELF]: packState(POSITION_ID.HANDSHAKE_REVERSED, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN_WITH_HAND_CHANGE_SELF]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
    },
    [packState(POSITION_ID.CROSSED_HANDS_RIGHT, COUNT.RIGHT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.CROSSED_HANDS_RIGHT, COUNT.LEFT),
        [MOVE_ID.TWO_HAND_TURN]: packState(POSITION_ID.OPEN, COUNT.LEFT),
    },
    [packState(POSITION_ID.CROSSED_HANDS_RIGHT, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.CROSSED_HANDS_RIGHT, COUNT.RIGHT),
    },
    [packState(POSITION_ID.CROSSED_HANDS_LEFT, COUNT.RIGHT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.CROSSED_HANDS_LEFT, COUNT.LEFT),
    },
    [packState(POSITION_ID.CROSSED_HANDS_LEFT, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.CROSSED_HANDS_LEFT, COUNT.RIGHT),
        [MOVE_ID.WALK_ENTRY]: packState(POSITION_ID.WALK, COUNT.RIGHT),
        [MOVE_ID.TWO_HAND_TURN]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
    },
    [packState(POSITION_ID.HAMMERLOCK_RIGHT, COUNT.RIGHT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.HAMMERLOCK_RIGHT, COUNT.LEFT),
        [MOVE_ID.STRAIGHT_TURN]: packState(POSITION_ID.OPEN, COUNT.LEFT),
    },
    [packState(POSITION_ID.HAMMERLOCK_RIGHT, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.HAMMERLOCK_RIGHT, COUNT.RIGHT),
    },
    [packState(POSITION_ID.HAMMERLOCK_LEFT, COUNT.RIGHT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.HAMMERLOCK_LEFT, COUNT.LEFT),
    },
    [packState(POSITION_ID.HAMMERLOCK_LEFT, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.HAMMERLOCK_LEFT, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_DOUBLE_TURN]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN_WITH_HAND_CHANGE]: packState(POSITION_ID.HANDSHAKE, COUNT.RIGHT),
    },
    [packState(POSITION_ID.HAMMERLOCK_RIGHT_SELF, COUNT.RIGHT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.HAMMERLOCK_RIGHT_SELF, COUNT.LEFT),
        [MOVE_ID.STRAIGHT_TURN]: packState(POSITION_ID.OPEN, COUNT.LEFT),
    },
    [packState(POSITION_ID.HAMMERLOCK_RIGHT_SELF, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.HAMMERLOCK_RIGHT_SELF, COUNT.RIGHT),
    },
    [packState(POSITION_ID.HAMMERLOCK_LEFT_SELF, COUNT.RIGHT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.HAMMERLOCK_LEFT_SELF, COUNT.LEFT),
    },
    [packState(POSITION_ID.HAMMERLOCK_LEFT_SELF, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.HAMMERLOCK_LEFT_SELF, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN_SELF]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
    },
    [packState(POSITION_ID.WALK, COUNT.RIGHT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.WALK, COUNT.LEFT),
        [MOVE_ID.WALK_EXIT_SIMPLE]: packState(POSITION_ID.OPEN, COUNT.LEFT),
        [MOVE_ID.WALK_EXIT_WIDE]: packState(POSITION_ID.WALK_FINISH, COUNT.LEFT),
    },
    [packState(POSITION_ID.WALK, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.WALK, COUNT.RIGHT),
    },
    [packState(POSITION_ID.WALK_FINISH, COUNT.RIGHT)]: {}, // nonsense
    [packState(POSITION_ID.WALK_FINISH, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.STRAIGHT_TURN]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
        [MOVE_ID.CLOSE_IN_TURN]: packState(POSITION_ID.CLOSED_HALF, COUNT.RIGHT),
        [MOVE_ID.TWO_HAND_TURN]: packState(POSITION_ID.CROSSED_HANDS_RIGHT, COUNT.RIGHT),
        [MOVE_ID.DEAD_TURN]: packState(POSITION_ID.OPEN, COUNT.RIGHT),
    },
    [packState(POSITION_ID.CUDDLING, COUNT.RIGHT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.CUDDLING, COUNT.LEFT),
    },
    [packState(POSITION_ID.CUDDLING, COUNT.LEFT)]: {
        [MOVE_ID.BASIC]: packState(POSITION_ID.CUDDLING, COUNT.RIGHT),
        [MOVE_ID.CUDDLING_EXIT]: packState(POSITION_ID.HANDSHAKE_REVERSED, COUNT.RIGHT),
    },
} as const;
